"""
Django settings for neo4j_django project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
from neo4j import GraphDatabase
from neo4j.exceptions import Neo4jError
from neomodel import config

BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-8%1efdp8^5hwcqje-mw1c7)$jtm6%&yxw=2^m8(h47&45+$+f4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'neoflix.apps.NeoflixConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'neo4j_django.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'neo4j_django.wsgi.application'

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'neoflix.authentication.Neo4jKeycloakAuthentication',
    ],
}


KEYCLOAK_CONFIG = {
    'KEYCLOAK_SERVER_URL': 'http://keycloak:8080/auth',
    'KEYCLOAK_REALM': 'neoflix',
    'KEYCLOAK_CLIENT_ID': 'neoflix',
    'KEYCLOAK_CLIENT_SECRET_KEY': 'e37444b4-e1c2-4455-a965-c0208f8472a5',
    'KEYCLOAK_CLIENT_GROUP_KEY': 'neoflix-user',
}


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

NEO4J_USER = 'neo4j'
NEO4J_PASSWORD = 'badbitch'
NEO4J_CONNECTION_STRING = 'neo4j://localhost:7687'
NEO4J_CONNECTION_URL = 'neo4j://neo4j:badbitch@localhost:7687/neoflix'

config.DATABASE_URL = NEO4J_CONNECTION_URL

DRIVER = GraphDatabase.driver(NEO4J_CONNECTION_STRING, auth=(NEO4J_USER, NEO4J_PASSWORD))

try:
    DRIVER.verify_connectivity()
    print('Connected to Neo4j')
except Neo4jError as e:
    print('Neo4j connection failed')
    print(e)
    DRIVER = None

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
